server:
  port: 8762
spring:
  application:
      name:eurekaserver      
eureka:
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
 client:
       register-with-eureka: false
       fetch-registry: false
cloud:
  config:
     enabled: false
     failFast: true
     uri: http://localhost:8888

    
    
      
